### ISSUE TITLE
Exclude test_data in source distribution

### ISSUE THREAD

**Issue by prabhu** [vidstige/ar#15]
Noticed that the test_data is not excluded in the source distribution published on pypi. Is it possible to configure the pyproject.toml, so that only the required source are published?

**Comment by vidstige** [comment]
Oh, I didn't notice that. That's certainly wrong. I'll look into that. PRs welcome if you know how to ignore that directory.

**Comment by prabhu** [comment]
@vidstige, I am not an expert in pyproject.toml myself. My colleagues usually does these things in my projects.

**Comment by vidstige** [comment]
I think I was able to fix it. I pushed a new release: v0.9

**Comment by prabhu** [comment]
I can still see the test_data folder in version 0.9. Maybe best to do a dry run and explore the .tar.gz files?

**Comment by vidstige** [comment]
I thought I did that. Maybe something is cached on the automatic github workflow 😑

**Comment by vidstige** [comment]
Alright, now it's removed from the source distribution as well (sdist)  as well. Check v.0.9.1 and see if it works better now.
